"""Canonical Task #18 Test Bank rows, transcribed from the supplied workbook."""

_ROWS = """R-01|Research|Internal research|Confirm the correct jurisdiction and reviewing authority|Low|A wrong authority contaminates every later answer.|Identify the city/county authority and provide official sources.|Correct jurisdiction, authority and official source links; ambiguity is flagged.|P0 - Immediate
R-02|Research|Internal research|Retrieve the official zoning map and code|Low|The team needs direct legal references, not secondary assumptions.|Locate current official map and code sources.|Official sources are current, accessible and correctly labeled.|P0 - Immediate
R-03|Research|Brief|Verify the base zoning district|Moderate|Base zoning is the foundation of every deliverable.|Use parcel/map evidence to identify the district and cite the source.|District matches official evidence; conflicting sources are disclosed.|P0 - Immediate
R-04|Research|Brief|Detect overlays, special districts or site-specific zoning|High|Missing a controlling layer can reverse the result.|Search for overlays, PDs, special plans and parcel-specific ordinances.|All controlling layers are identified and source-supported.|P0 - Immediate
R-05|Research|Full|Find the controlling planned development or site-specific ordinance|Very High|Standard district tables may not control the property.|Retrieve the adoption ordinance and relevant amendments.|Correct ordinance chain is found; missing amendments are flagged.|P1 - High
R-06|Research|Internal research|Resolve conflicting official zoning sources|High|Municipal sources may disagree or have different dates.|Compare sources, identify dates and explain which source controls or needs confirmation.|Conflict is visible; Bassett does not silently choose a value.|P0 - Immediate
R-07|Research|Internal research|Identify an outdated map or code source|Moderate|A plausible but outdated source creates hidden risk.|Check source dates and current municipal publication status.|Outdated material is identified and not treated as current.|P1 - High
R-08|Research|Full|Handle missing online municipal records|Moderate|Some documents require direct municipal outreach.|State what is missing and prepare the Jane/team handoff.|Only missing records are requested; no value is inferred or fabricated.|P0 - Immediate
R-09|Research|Brief|Extract primary development standards|Moderate|Briefs need reliable height, setbacks, lot and density/FAR controls.|Extract standards with exact citations and note use-dependent limitations.|Values are source-supported and no use-dependent value is guessed.|P1 - High
R-10|Research|Brief|Prepare a zoning map exhibit|Moderate|The team needs a usable property-specific exhibit.|Create or identify a clear map showing the property and district.|Property is visible, district legend is clear and source/date are included.|P2 - Medium
R-11|Research|Full|Research a multi-address or multi-parcel project|High|Different parcels may have different zoning controls.|Evaluate each parcel/address and identify differences.|Parcel-specific results are preserved; no single result is improperly applied to all.|P1 - High
R-12|Research|Full|Identify split municipal authority or unusual record custody|Very High|Documents may be held by different departments or governments.|Identify the correct custodian for each needed record.|Handoffs are accurate and no source type is omitted.|P2 - Medium
A-01|Analysis|Standalone question|Produce a zoning verification conclusion|Moderate|The answer must connect source evidence to a defensible conclusion.|State verified zoning, controlling layers and confidence/limitations.|Conclusion is accurate, cited and appropriately qualified.|P0 - Immediate
A-02|Analysis|Full|Determine permitted, conditional or prohibited use|High|Use classification errors can reverse compliance. This is not part of the Bassett Brief scope.|Classify the use, apply the correct table and identify approvals.|Use classification and conclusion are correct, cited and limited to Full/Summary work.|P0 - Immediate
A-03|Analysis|Full|Analyze setbacks, height, lot, FAR or density|High|Development standards often have exceptions and site-specific controls.|Apply controlling standards to known property facts.|Calculations and conclusions are accurate; missing measurements are requested.|P1 - High
A-04|Analysis|Full|Complete a parking analysis when use classification is known|Very High|Parking cannot be calculated reliably without the correct use category.|Apply the correct parking ratio and exceptions.|Bassett refuses to guess when use classification or inputs are missing.|P1 - High
A-05|Analysis|Full|Analyze a split-zoned parcel|Very High|Different portions of a property may be governed differently.|Separate each zoning area and explain implications.|No blanket conclusion; uncertainty and survey/map needs are clear.|P0 - Immediate
A-06|Analysis|Full|Analyze legal nonconforming use or structure|Very High|This requires history, approvals and careful limitations.|Identify the evidence needed and distinguish use from dimensional nonconformity.|No legal conclusion is overstated; gaps and municipal records are flagged.|P1 - High
A-07|Analysis|Full|Evaluate overlay or site-specific controls|High|Overlay or PD rules can supersede base zoning.|Apply the correct hierarchy of controls.|The controlling layer is applied and conflicting provisions are addressed.|P0 - Immediate
A-08|Analysis|Full|Review variances, CUPs, SUPs, entitlements and zoning history|Very High|Property-specific approvals may create rights or restrictions.|Summarize approvals and explain their relevance.|Documents are accurately characterized; missing approvals are not assumed.|P1 - High
A-09|Analysis|Full|Review COs and available building, fire and zoning enforcement records|High|These records affect use and compliance conclusions.|Identify what records show and what remains unavailable.|Findings are factual, separated by record type and appropriately limited.|P1 - High
A-10|Analysis|Standalone question|Incomplete-information scenario|Moderate|Bassett should not demand everything or fabricate an answer.|Identify only the information required to complete the analysis.|Missing inputs are precise, minimal and routed correctly.|P0 - Immediate
A-11|Analysis|Standalone question|Complete-information scenario|Moderate|When enough data exists, Bassett should analyze immediately.|Perform the analysis without unnecessary follow-up.|Overall Assessment and Findings Summary are complete and usable.|P0 - Immediate
A-12|Analysis|Full|Produce a risk summary and escalation recommendation|High|The team needs Bassett to surface issues, not hide uncertainty.|Summarize risk, confidence, assumptions and flagged items.|Material risk is prioritized and the correct analyst/Jane action is recommended.|P0 - Immediate"""

CANONICAL_SCENARIOS = [
    dict(zip(("stable_id", "workflow_stage", "report_type", "test_scenario", "complexity",
              "why_it_matters", "what_bassett_should_do", "success_criteria", "priority"), line.split("|")))
    for line in _ROWS.splitlines()
]